### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Rudxain**
- Converted `getColors` into a "pure" fn (for easier maintainability)
- Made `scheme` local/private
- Rename `getNumberLength` to `digitCount` (less ambiguous)
- Added doc-comments
- etc...

### CODE REVIEW

**Comment by mevdschee** [comment]
Hi, thank you for your changes. Some may actually improve the code. You write:

>remove len, because of warnings

and

>remove const warnings

Can you tell me which compiler and flags you used to get these warnings?

Kind regards, Maurits

**Comment by Rudxain** [comment]
> Can you tell me which compiler and flags you used to get these warnings?

I used the exact command in the README.md, the only diff being I added `-O3`.

The `len` warnings was probably because I specified the wrong param type. The `const` warnings were because the immutability would be "discarded" (that's what GCC said) when passed to a fn that didn't treat the argument as `const` (for example, when passing a `const board` to `rotateBoard`, because there's an in-place mutation)

**Comment by mevdschee** [comment]
>I used the exact command in the README.md, the only diff being I added -O3.

Interesting. I'm going to try that too and see what happens.

**Comment by mevdschee** [comment]
Like in your first commit, I reduced the number of global variables, see: 4ec6d5c57c1dff008926c6c06f7b559f44082c63

I hope you like that as a code improvement. Kind regards, Maurits

**Comment by Rudxain** [comment]
> Like in your first commit, I reduced the number of global variables, see: [4ec6d5c](https://github.com/mevdschee/2048.c/commit/4ec6d5c57c1dff008926c6c06f7b559f44082c63)
> 
> I hope you like that as a code improvement. Kind regards, Maurits

Thank you. And, about that, I was considering reverting the change, because there's only 2 global mutables, and they're used in a some (not all) fns, and they're only mutated in 1 or 2 places. But if this game/program gets more complex in the future, using local vars will be worth it! (Because of easier testing/debugging, despite making the code slightly more explicit/verbose)

**Comment by mevdschee** [comment]
I also explained some ANSI sequences that you seemed hard to understand, see: bd0cd2f98b412d10c8eb5759721011cb5fd62fc6

see also: https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences

**Comment by mevdschee** [comment]
It seemed you struggled with the multiple return value of the 'getColors' function. I added some comments, see: 065ebb65ced8a4a4a5174bda879521d756997415

see also: https://stackoverflow.com/questions/2620146/how-do-i-return-multiple-values-from-a-function-in-c

**Comment by Rudxain** [comment]
> I also explained some ANSI sequences

Thank you! But I should've read more about ANSI esc-seqs. I think that one comment saying "this program uses ANSI sequences" would've been enough for me (probably 😅).

But maybe we should convert those comments into self-commenting code? Some of those `printf` calls can be turned into named macros and fns, and some IDEs and text-editors (like VSCode) treat nearby comments as doc-comments, allowing for more descriptive doc-hints

> It seemed you struggled with the multiple return value of the 'getColors' function.

Yes, I'm used to destructuring syntax, so I used explicit indices as an alternative (the best I could think of, lol).

And thank you (again) for the comments and links!

**Comment by mevdschee** [comment]
>Rename getNumberLength to digitCount (less ambiguous)

I applied this, see: d1ce5203f36a71d091331be5821a8c535de6e9c4

**Comment by mevdschee** [comment]
>And thank you (again) for the comments and links!

You are welcome! It seems that you are an experienced JS programmer (using 'const' and pure functions). It is inspiring to read your adjustments and I also want to thank you for taking the time to improve the code with a fresh look on modern programming. I couldn't apply all changes, but I did apply as many as I could while maintaining compatibility.

>But maybe we should convert those comments into self-commenting code?

That is what be doing what the 'ncurses' library does. I didn't pursue that path to avoid dependencies.

Take care! Kindest regards, Maurits

**Comment by mevdschee** [comment]
I merged and you are now in the contributors list, see: https://github.com/mevdschee/2048.c/graphs/contributors

**Comment by mevdschee** [comment]
Thank you again for your insights and adjustments.

**Comment by Rudxain** [comment]
> It seems that you are an experienced JS programmer.

I guess 😅 but I'm still learning about async programming without callbacks (`Promise`s, `await`, etc...)

> It is inspiring to read your adjustments and I also want to thank you for taking the time to improve the code with a fresh look on modern programming. I couldn't apply all changes, but I did apply as many as I could while maintaining compatibility.

Thank you too. And it's okay, it's good to make a gradual transition.

> That is more or less what the 'ncurses' library does. I didn't pursue that path to avoid dependencies.

That's interesting, I learned something new about ncurses!

> I merged and you are now in the contributors list

I planned to commit some other changes later, that's why I marked the PR as "Draft". But it's okay! I need more time to focus on other projects and IRL stuff. When I have more spare time (probably some months later) I'll re-review and (possibly) open another PR

**Comment by mevdschee** [comment]
> I planned to commit some other changes later, that's why I marked the PR as "Draft".

I know, but I merged so that you would get credit for the changes that you've made.

>I'll re-review and (possibly) open another PR

I like that: smaller PRs are easier to review.

**Pull request merged**
