### PR TITLE
2048.c highscores table

### PR DESCRIPTION
**Pull request by farooqkz**
This is fine for shell servers, there is a SCORE_FILE where the 5 best scores are listed.
I did not debug it much but i implemented it on my own computer and worked fine till now.

### CODE REVIEW

**Comment by farooghkz** [comment]
.I modify: it's not multi-player, just a highscores table

**Comment by farooghkz** [comment]
Code was changed: If you run it, first it will try to use `/var/games/2048scores` if it can, if it couldn't(e.g. it doesn't have access) it will try to use `/home/USER/.2048scores` where `USER` is player's username, if it couldn't use the 2nd score file, it will quit with an error message, for both score files, it will create them if they didn't exist.
All these happens after player played the game, this means if there was any problem highscores table, player can play.

**Comment by farooqkz** [comment]
@mevdschee: Would this be merged at all?

**Comment by Xiaomu0** [comment]
Nice try to add this feature, but your codes seems haven't be completed (or in test situation because some hard codes still exist like ```"foo"```) IMHO and might let this tiny program to be complicated, such as the installation steps.
Anyway, have fun!

**Comment by mevdschee** [comment]
@Xiaomu0 thank you for your feedback.. appreciated.

**Comment by farooqkz** [comment]
@X1aomu thanks for the feedback.
perhaps the code is not clean and completed but what you've said is not correct:
the function `mkscore_file` generates a default score file, all foos have a score of 700.
So I don't see any problem with "foo".

**Comment by X1aomu** [comment]
@farooqkz Emm... I just simply think that the word "foo" should not appear in the code, which is meaningless. In my opinion, if you really want to place a default string in generated file, you should write down "DEFAULT_NAME" instead of "foo".

By the way, I've browsed your code in more detail this time and I would like to give you some other sugestions to help you improve your code:

* You may not return score value in main function (Is this what you wish? I couldn't even find a return value of highscores_() function...)
* You are supposed to use the same indent method as original code
* You sould rewrite your README.md since has lost sync with your code
* You may not expect user to change source code to change the behavour of the program
* The installation steps are too complicated. You may need to write a Makefile to do them automatically

Hope this sugestions helpful.

**Comment by farooqkz** [comment]
The code was written more than 1 year ago and modified months later and it doesn't have its coherence. So I should review and rewrite it.
@mevdschee Could you please add a "WIP" label?

**Comment by mevdschee** [comment]
Maybe a good idea for a fork? I'm not a competitive gamer ;-)

**Comment by farooqkz** [comment]
@mevdschee 
Can I use your username in my fork in the default high score file?

**Comment by mevdschee** [comment]
> Can I use your username in my fork in the default high score file?
Sure

**Pull request closed without merging**
